/* Copyright (c) 2008  ATMEL Corporation
   All rights reserved.

   Redistribution and use in source and binary forms, with or without
   modification, are permitted provided that the following conditions are met:

   * Redistributions of source code must retain the above copyright
     notice, this list of conditions and the following disclaimer.
   * Redistributions in binary form must reproduce the above copyright
     notice, this list of conditions and the following disclaimer in
     the documentation and/or other materials provided with the
     distribution.
   * Neither the name of the copyright holders nor the names of
     contributors may be used to endorse or promote products derived
     from this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
  POSSIBILITY OF SUCH DAMAGE.
*/
/*
  $Id: mac_event.c,v 1.1 2009/05/20 20:52:01 mvidales Exp $
*/

// Includes
#include <stdlib.h>
#include "mac.h"
#include "mac_event.h"
#include "mac_data.h"
#include "mac_scan.h"
#include "mac_associate.h"
#include "radio.h"
#include "stdio.h"
#include "timer.h"
#include "system.h"

/**
   @ingroup mac
   @{
   @defgroup mac_event MAC event handler
   @{

   This module processes events generated by the MAC.  Events include
   interrupts from the radio chip, and expired timer events.  The
   macTask() function should be called periodically from the main loop
   or OS process to process these events. @see mac_timer
*/

// Globals

/// Number of events in event queue
#define MAX_EVENTS 10

/// Structure that defines the event queue.
typedef struct {
    volatile u8 head;   ///< The index of the last available event
    volatile u8 tail;   ///< The index of the first available event
    event_object_t event_object[MAX_EVENTS]; ///< List of events in queue
} event_queue_t;
event_queue_t event_queue; ///< The event queue itself

// Implementation

/**
      Checks for any pending events in the queue.

    returns:  True if there is a pending event, else false.
*/
u8
mac_event_pending(void)
{
    return (event_queue.head != event_queue.tail);
}


/**
      Puts an event into the queue of events.

    param:  object is a pointer to the event to add to queue.
*/
void
mac_put_event(event_object_t *object)
{
    u8 newhead;

    if ((event_queue.head + 1) % MAX_EVENTS == event_queue.tail)
        // queue full, get outta here
        return;

    newhead = event_queue.head;

    // store in queue
    event_queue.event_object[newhead] = *object;

    // calculate new head index
    newhead++;
    if (newhead >= MAX_EVENTS)
        newhead = 0;
    event_queue.head = newhead;
}

/**
      Pulls an event from the event queue.  Assumes that there is
    an event in the queue.  Be sure that mac_event_pending() returns
    true before calling this function.

    returns:  Pointer to the event object, or garbage data if the queue
    is empty.
*/
event_object_t *
mac_get_event(void)
{
    event_object_t *object = NULL;
    volatile u8 newtail;

    newtail = event_queue.tail;

    object = &(event_queue.event_object[newtail]);

    // calculate new tail
    newtail++;
    if (newtail >= MAX_EVENTS)
        newtail = 0;

    event_queue.tail = newtail;

    return(object);
}

/**
     This is the main loop task for the MAC.  Called by the main
   "forever" loop or by an OS task or thread.  This function processes
   interrupt events that are stored in the event queue by the radio or
   timer.
*/
void
macTask(void)
{
    event_object_t *event;
    event = 0;

    while(mac_event_pending())
    {
        event = mac_get_event();
 //debugMsgStr("\r\n MacEvent=0x");
 //debugMsgHex(event->event);
        switch (event->event)
        {
		   case MAC_EVENT_TIMER:
			   // Timer has expired, just callback the stored function pointer
			   ((void (*)(void))event->data)();  // cast data to function pointer
			   break;

			case MAC_EVENT_DATA_RX:
				if (macConfig.associated)
				{
					// Wake up
					if (NODETYPE != ENDDEVICE)
						macChildIsAwake((ftData*)(mac_buffer_rx+1));

					u16 Dest = ((ftData*)(mac_buffer_rx+1))->finalDestAddr;

					// Received a data frame, process it or route it
					if (Dest == macConfig.shortAddress) 	// This data frame is for this node
						macDataIndication();
					else if (Dest == BROADCASTADDR)
// TODO: chnage the processing of broadcast data , for now use broadcast data like regular data
						macDataIndication();
					else
					{
						// Route the packet up/down stream
						if (NODETYPE != ENDDEVICE)
							macRouteData();
					}
				}
				break;

			case MAC_EVENT_BEACON_REQUEST:
				// Generate and send the beacon.
				if (NODETYPE == COORD)
					sendBeaconFrame();
				else if (NODETYPE == ROUTER && macConfig.associated)
				{// TODO: why does it need to be delayed -- shouldn't the CDMA take care of this
					macSetAlarm(3, sendBeaconFrame);
				}
				break;

			case MAC_EVENT_BEACON_RECEIVED:
				// A beacon has been received as a result of an active scan.
				// Record the pan descriptor and store it until the scan has
				// completed.
				debugMsgStr("\r\nmacBeaconReceived<-");
				if (!macConfig.associated)
					mac_logPanDescriptors();
				break;

			case MAC_EVENT_ASSOCIATION_REQUEST:
				// Pan Coord has received this request.
				if (NODETYPE == COORD)
					macAssociationResponse();
				else if (NODETYPE == ROUTER && macConfig.associated)
				{
					// Send this packet along to parent
					macRouteAssociateRequest();
				}
				break;

			case MAC_EVENT_ASSOCIATION_RESPONSE:
				// End device has recieved this response.
				if (NODETYPE != COORD)
				{
					ftAssocRespDirect * resp = (ftAssocRespDirect*) (mac_buffer_rx+1);
					//if (*((u16*)(mac_buffer_rx+1)) == FCF_ASSOC_RESP_DIRECT) // Direct to MAC Addr?
					if (resp->fcf == FCF_ASSOC_RESP_DIRECT)
					{
						// this is a new node, do the association thing
						macConfig.associated = true;
					//	macConfig.parentShortAddress = ((ftAssocRespDirect*)(mac_buffer_rx+1))->srcAddr;
					//	macConfig.shortAddress = ((ftAssocRespDirect*)(mac_buffer_rx+1))->shortAddr;
					//	radioSetShortAddress(macConfig.shortAddress);
						macAssociationConfirm();
					}
					else
					{
						// we are indirect, so just send this packet along.
						if (NODETYPE == ROUTER && macConfig.associated)
							macRouteAssociateResponse();
					}
				}
				break;

			case MAC_EVENT_ROUTE:
				// Routing packet received, forward it
				if (NODETYPE == ROUTER && macConfig.associated)
					macForwardRoutingPacket();
				break;

			case MAC_EVENT_ACCESS_FAIL:
				// Channel access failure
				appPacketSendAccessFail();
				break;

			case MAC_EVENT_NACK:
				// Packet failed to be sent, alert application
				appPacketSendFailed();
				break;

			case MAC_EVENT_ACK:
				// Packet got through, notify application
				appPacketSendSucceed();
				break;

			default:
				 debugMsgStr("\r\n Invalid MacEvent!");
				break;
        }
    }
}


